namespace DotMake.CommandLine
{
    /// <summary>
    /// Provides extension methods for <see cref="Cli"/>. These are usually automatically generated by the source generator
    /// when current project supports a specific feature through a dependency,
    /// e.g. when you add package <c>Microsoft.Extensions.DependencyInjection</c>, dependency injection related extension
    /// methods will be available here. 
    /// </summary>
    public class CliExtensions
    {
        internal CliExtensions()
        {
            
        }
    }
}
