// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.8.2.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.41305
// Generation: 1

namespace GeneratedCode
{
    /// <inheritdoc />
    public class CliCommandAsDelegate_a5kez68Builder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public CliCommandAsDelegate_a5kez68Builder()
        {
            DefinitionType = typeof(global::GeneratedCode.CliCommandAsDelegate_a5kez68);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'CliCommandAsDelegate_a5kez68' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("CliCommandAsDelegate_a5kez68")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "CliCommandAsDelegate_a5kez68");

            // Option for 'option1' property
            var option0 = new global::System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("option1")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "option1");
            command.Add(option0);

            // Argument for 'argument1' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("argument1")
            )
            {
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::GeneratedCode.CliCommandAsDelegate_a5kez68();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::GeneratedCode.CliCommandAsDelegate_a5kez68)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.option1 = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.argument1 = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(async (parseResult, cancellationToken) =>
            {
                var definitionInstance = bindingContext.Bind<global::GeneratedCode.CliCommandAsDelegate_a5kez68>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult, cancellationToken);
                var exitCode = 0;
                await definitionInstance.RunAsync();

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::GeneratedCode.CliCommandAsDelegate_a5kez68Builder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
