// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.0.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.46508
// Generation: 1

namespace GeneratedCode
{
    /// <inheritdoc />
    [DotMake.CommandLine.CliCommandAttribute]
    public class CliCommandAsDelegate_5v59h64 : global::DotMake.CommandLine.CliCommandAsDelegate
    {
        /// <inheritdoc />
        [global::DotMake.CommandLine.CliArgumentAttribute]
        public string argument1 { get; set; }

        /// <inheritdoc />
        [DotMake.CommandLine.CliOptionAttribute]
        public bool option1 { get; set; }

        /// <inheritdoc />
        public void Run()
        {
            InvokeDelegate
            (
                "5v59h64",
                new object[]
                {
                    argument1, 
                    option1, 
                }
            );
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            // Register this definition class so that it can be found by the command as delegate hash.
            Register<GeneratedCode.CliCommandAsDelegate_5v59h64>("5v59h64");
        }
    }
}
