// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.1.0.0
// Roslyn (Microsoft.CodeAnalysis) v5.0.25.52411
// Generation: 1

namespace GeneratedCode
{
    /// <inheritdoc />
    public class CliCommandAsDelegate_fsqgtf8Builder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public CliCommandAsDelegate_fsqgtf8Builder()
        {
            DefinitionType = typeof(global::GeneratedCode.CliCommandAsDelegate_fsqgtf8);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'CliCommandAsDelegate_fsqgtf8' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("CliCommandAsDelegate_fsqgtf8")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "CliCommandAsDelegate_fsqgtf8");

            // Option for 'option2' property
            var option0 = new global::System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("option2")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "option2");
            command.Add(option0);

            // Argument for 'argument2' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("argument2")
            )
            {
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::GeneratedCode.CliCommandAsDelegate_fsqgtf8();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::GeneratedCode.CliCommandAsDelegate_fsqgtf8)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.option2 = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.argument2 = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(async (parseResult, cancellationToken) =>
            {
                var definitionInstance = bindingContext.Bind<global::GeneratedCode.CliCommandAsDelegate_fsqgtf8>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult, cancellationToken);
                var exitCode = 0;
                await definitionInstance.RunAsync();

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::GeneratedCode.CliCommandAsDelegate_fsqgtf8Builder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
