// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.6.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.26210
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class EnumerableCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public EnumerableCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.EnumerableCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.EnumerableCliCommand CreateInstance()
        {
            return new TestApp.Commands.EnumerableCliCommand();
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild()
        {
            // Command for 'EnumerableCliCommand' class
            var commandName = Namer.GetCommandName("EnumerableCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "EnumerableCliCommand");

            // Option for 'OptEnumerable' property
            var option0Name = Namer.GetOptionName("OptEnumerable");
            var option0 = new System.CommandLine.Option<System.Collections.Generic.IEnumerable<int>>
            (
                option0Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<System.Collections.Generic.IEnumerable<int>, int>
                (
                    array => (int[])array,
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "OptEnumerable");
            command.Add(option0);

            // Option for 'OptList' property
            var option1Name = Namer.GetOptionName("OptList");
            var option1 = new System.CommandLine.Option<System.Collections.Generic.List<string>>
            (
                option1Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<System.Collections.Generic.List<string>, string>
                (
                    array => new System.Collections.Generic.List<string>((string[])array),
                    null
                ),
            };
            Namer.AddShortFormAlias(option1, "OptList");
            command.Add(option1);

            // Option for 'OptEnumArray' property
            var option2Name = Namer.GetOptionName("OptEnumArray");
            var option2 = new System.CommandLine.Option<System.IO.FileAccess[]>
            (
                option2Name
            )
            {
                AllowMultipleArgumentsPerToken = true,
                Required = false,
                CustomParser = GetArgumentParser<System.IO.FileAccess[], System.IO.FileAccess>
                (
                    array => (System.IO.FileAccess[])array,
                    null
                ),
            };
            Namer.AddShortFormAlias(option2, "OptEnumArray");
            command.Add(option2);

            // Option for 'OptCollection' property
            var option3Name = Namer.GetOptionName("OptCollection");
            var option3 = new System.CommandLine.Option<System.Collections.ObjectModel.Collection<int?>>
            (
                option3Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<System.Collections.ObjectModel.Collection<int?>, int?>
                (
                    array => new System.Collections.ObjectModel.Collection<int?>(System.Linq.Enumerable.ToList((int?[])array)),
                    null
                ),
            };
            Namer.AddShortFormAlias(option3, "OptCollection");
            command.Add(option3);

            // Option for 'OptHashSet' property
            var option4Name = Namer.GetOptionName("OptHashSet");
            var option4 = new System.CommandLine.Option<System.Collections.Generic.HashSet<string>>
            (
                option4Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<System.Collections.Generic.HashSet<string>, string>
                (
                    array => new System.Collections.Generic.HashSet<string>((string[])array),
                    null
                ),
            };
            Namer.AddShortFormAlias(option4, "OptHashSet");
            command.Add(option4);

            // Option for 'OptQueue' property
            var option5Name = Namer.GetOptionName("OptQueue");
            var option5 = new System.CommandLine.Option<System.Collections.Generic.Queue<System.IO.FileInfo>>
            (
                option5Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<System.Collections.Generic.Queue<System.IO.FileInfo>, System.IO.FileInfo>
                (
                    array => new System.Collections.Generic.Queue<System.IO.FileInfo>((System.IO.FileInfo[])array),
                    null
                ),
            };
            Namer.AddShortFormAlias(option5, "OptQueue");
            command.Add(option5);

            // Option for 'OptCustomList' property
            var option6Name = Namer.GetOptionName("OptCustomList");
            var option6 = new System.CommandLine.Option<TestApp.Commands.CustomList<string>>
            (
                option6Name
            )
            {
                Required = false,
                CustomParser = GetArgumentParser<TestApp.Commands.CustomList<string>, string>
                (
                    array => new TestApp.Commands.CustomList<string>((string[])array),
                    null
                ),
            };
            Namer.AddShortFormAlias(option6, "OptCustomList");
            command.Add(option6);

            // Argument for 'ArgIList' property
            var argument0Name = Namer.GetArgumentName("ArgIList");
            var argument0 = new System.CommandLine.Argument<System.Collections.IList>
            (
                argument0Name
            )
            {
                CustomParser = GetArgumentParser<System.Collections.IList, string>
                (
                    array => (string[])array,
                    null
                ),
            };
            argument0.Arity = System.CommandLine.ArgumentArity.OneOrMore;
            command.Add(argument0);

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the values for the parent command accessors

                //  Set the parsed or default values for the directives

                //  Set the parsed or default values for the options
                targetClass.OptEnumerable = GetValueForOption(parseResult, option0);
                targetClass.OptList = GetValueForOption(parseResult, option1);
                targetClass.OptEnumArray = GetValueForOption(parseResult, option2);
                targetClass.OptCollection = GetValueForOption(parseResult, option3);
                targetClass.OptHashSet = GetValueForOption(parseResult, option4);
                targetClass.OptQueue = GetValueForOption(parseResult, option5);
                targetClass.OptCustomList = GetValueForOption(parseResult, option6);

                //  Set the parsed or default values for the arguments
                targetClass.ArgIList = GetValueForArgument(parseResult, argument0);

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = (TestApp.Commands.EnumerableCliCommand) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.EnumerableCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
