// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.5.8.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.26210
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class InheritanceCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public InheritanceCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.InheritanceCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.InheritanceCliCommand CreateInstance()
        {
            return new TestApp.Commands.InheritanceCliCommand();
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild()
        {
            // Command for 'InheritanceCliCommand' class
            var commandName = Namer.GetCommandName("InheritanceCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "InheritanceCliCommand");

            // Option for 'Username' property
            var option0Name = Namer.GetOptionName("Username");
            var option0 = new System.CommandLine.Option<string>
            (
                option0Name
            )
            {
                Description = "Username of the identity performing the command",
                Required = false,
                DefaultValueFactory = _ => "admin",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Username");
            command.Add(option0);

            // Option for 'Password' property
            var option1Name = Namer.GetOptionName("Password");
            var option1 = new System.CommandLine.Option<string>
            (
                option1Name
            )
            {
                Description = "Password of the identity performing the command",
                Required = true,
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option1, "Password");
            command.Add(option1);

            // Argument for 'Department' property
            var argument0Name = Namer.GetArgumentName("Department");
            var argument0 = new System.CommandLine.Argument<string>
            (
                argument0Name
            )
            {
                Description = "Department of the identity performing the command (interface)",
                DefaultValueFactory = _ => "Accounting",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the values for the parent command accessors

                //  Set the parsed or default values for the directives

                //  Set the parsed or default values for the options
                targetClass.Username = GetValueForOption(parseResult, option0);
                targetClass.Password = GetValueForOption(parseResult, option1);

                //  Set the parsed or default values for the arguments
                targetClass.Department = GetValueForArgument(parseResult, argument0);

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = (TestApp.Commands.InheritanceCliCommand) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run();

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.InheritanceCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
