// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.6.0.0
// Roslyn (Microsoft.CodeAnalysis) v5.900.26.38015
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class NameConflictCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public NameConflictCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.NameConflictCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            var namer = bindingContext.NamerMap[this];

            // Command for 'NameConflictCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    namer.GetCommandName("NameConflictCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            namer.AddShortFormAlias(command, "NameConflictCliCommand");

            // Option for 'Option1' property
            var option0 = new global::System.CommandLine.Option<string>
            (
                namer.GetOptionName("Option1")
            )
            {
                Description = "Description for Option1",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption1",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            namer.AddShortFormAlias(option0, "Option1");
            command.Add(option0);

            // Option for 'Option2' property
            var option1 = new global::System.CommandLine.Option<string>
            (
                namer.GetOptionName("Option2")
            )
            {
                Description = "Conflicting option",
                Required = true,
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            namer.AddShortFormAlias(option1, "Option2");
            command.Add(option1);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.NameConflictCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.NameConflictCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.Option1 = bindingContext.GetValue(parseResult, option0);
                definitionInstance.Option2 = bindingContext.GetValue(parseResult, option1);

                // Set the parsed or default values for the arguments
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.NameConflictCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.NameConflictCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class SubCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public SubCliCommandBuilder()
            {
                DefinitionType = typeof(global::TestApp.Commands.NameConflictCliCommand.SubCliCommand);
                ParentDefinitionType = typeof(global::TestApp.Commands.NameConflictCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            /// <inheritdoc />
            protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
            {
                var namer = bindingContext.NamerMap[this];

                // Command for 'SubCliCommand' class
                var command = IsRoot
                    ? new global::System.CommandLine.RootCommand()
                    : new global::System.CommandLine.Command
                    (
                        namer.GetCommandName("SubCliCommand")
                    );
                var rootCommand = command as global::System.CommandLine.RootCommand;
                command.Description = "A nested level 1 sub-command";
                namer.AddShortFormAlias(command, "SubCliCommand", "c");

                bindingContext.CommandMap[command] = DefinitionType;
                bindingContext.CreatorMap[DefinitionType] = () =>
                {
                    return new global::TestApp.Commands.NameConflictCliCommand.SubCliCommand();
                };
                bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                {
                    var definitionInstance = (global::TestApp.Commands.NameConflictCliCommand.SubCliCommand)instance;

                    // Set the values for the command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options

                    // Set the parsed or default values for the arguments
                };

                command.SetAction(parseResult =>
                {
                    var definitionInstance = bindingContext.Bind<global::TestApp.Commands.NameConflictCliCommand.SubCliCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    cliContext.ShowHelp();

                    return exitCode;
                });

                return command;
            }

            [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new global::TestApp.Commands.GeneratedCode.NameConflictCliCommandBuilder.SubCliCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }

            /// <inheritdoc />
            public class Sub2CommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
            {
                /// <inheritdoc />
                public Sub2CommandBuilder()
                {
                    DefinitionType = typeof(global::TestApp.Commands.NameConflictCliCommand.SubCliCommand.Sub2Command);
                    ParentDefinitionType = typeof(global::TestApp.Commands.NameConflictCliCommand.SubCliCommand);
                    ChildDefinitionTypes = null;
                    NameAutoGenerate = null;
                    NameCasingConvention = null;
                    NamePrefixConvention = null;
                    ShortFormAutoGenerate = null;
                    ShortFormPrefixConvention = null;
                }

                /// <inheritdoc />
                protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
                {
                    var namer = bindingContext.NamerMap[this];

                    // Command for 'Sub2Command' class
                    var command = IsRoot
                        ? new global::System.CommandLine.RootCommand()
                        : new global::System.CommandLine.Command
                        (
                            namer.GetCommandName("Sub2Command")
                        );
                    var rootCommand = command as global::System.CommandLine.RootCommand;
                    command.Description = "Conflicting sub-command";
                    namer.AddShortFormAlias(command, "Sub2Command", "c");

                    bindingContext.CommandMap[command] = DefinitionType;
                    bindingContext.CreatorMap[DefinitionType] = () =>
                    {
                        return new global::TestApp.Commands.NameConflictCliCommand.SubCliCommand.Sub2Command();
                    };
                    bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                    {
                        var definitionInstance = (global::TestApp.Commands.NameConflictCliCommand.SubCliCommand.Sub2Command)instance;

                        // Set the values for the command accessors

                        // Set the parsed or default values for the directives

                        // Set the parsed or default values for the options

                        // Set the parsed or default values for the arguments
                    };

                    command.SetAction(parseResult =>
                    {
                        var definitionInstance = bindingContext.Bind<global::TestApp.Commands.NameConflictCliCommand.SubCliCommand.Sub2Command>(parseResult);

                        // Call the command handler
                        var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                        var exitCode = 0;
                        cliContext.ShowHelp();

                        return exitCode;
                    });

                    return command;
                }

                [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
                internal static void Initialize()
                {
                    var commandBuilder = new global::TestApp.Commands.GeneratedCode.NameConflictCliCommandBuilder.SubCliCommandBuilder.Sub2CommandBuilder();

                    // Register this command builder so that it can be found by the definition class
                    // and it can be found by the parent definition class if it's a nested/external child.
                    commandBuilder.Register();
                }
            }
        }
    }
}
