// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.5.8.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.26210
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class PartialCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public PartialCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.PartialCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.PartialCliCommand CreateInstance()
        {
            return new TestApp.Commands.PartialCliCommand();
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild()
        {
            // Command for 'PartialCliCommand' class
            var commandName = Namer.GetCommandName("PartialCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            command.Description = "A cli command with partial class";
            Namer.AddShortFormAlias(command, "PartialCliCommand");

            // Option for 'Option1' property
            var option0Name = Namer.GetOptionName("Option1");
            var option0 = new System.CommandLine.Option<string>
            (
                option0Name
            )
            {
                Description = "Description for Option1",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption1",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Option1");
            command.Add(option0);

            // Option for 'Option2' property
            var option1Name = Namer.GetOptionName("Option2");
            var option1 = new System.CommandLine.Option<string>
            (
                option1Name
            )
            {
                Description = "Description for Option2",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption2",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option1, "Option2");
            command.Add(option1);

            // Argument for 'Argument1' property
            var argument0Name = Namer.GetArgumentName("Argument1");
            var argument0 = new System.CommandLine.Argument<string>
            (
                argument0Name
            )
            {
                Description = "Description for Argument1",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the values for the parent command accessors

                //  Set the parsed or default values for the directives

                //  Set the parsed or default values for the options
                targetClass.Option1 = GetValueForOption(parseResult, option0);
                targetClass.Option2 = GetValueForOption(parseResult, option1);

                //  Set the parsed or default values for the arguments
                targetClass.Argument1 = GetValueForArgument(parseResult, argument0);

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = (TestApp.Commands.PartialCliCommand) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run();

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.PartialCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class PartialNestedCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public PartialNestedCliCommandBuilder()
            {
                DefinitionType = typeof(TestApp.Commands.PartialCliCommand.PartialNestedCliCommand);
                ParentDefinitionType = typeof(TestApp.Commands.PartialCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            private TestApp.Commands.PartialCliCommand.PartialNestedCliCommand CreateInstance()
            {
                return new TestApp.Commands.PartialCliCommand.PartialNestedCliCommand();
            }

            /// <inheritdoc />
            protected override System.CommandLine.Command DoBuild()
            {
                // Command for 'PartialNestedCliCommand' class
                var commandName = Namer.GetCommandName("PartialNestedCliCommand");
                var command = IsRoot
                    ? new System.CommandLine.RootCommand()
                    : new System.CommandLine.Command(commandName);
                var rootCommand = command as System.CommandLine.RootCommand;
                Namer.AddShortFormAlias(command, "PartialNestedCliCommand");

                // Option for 'InputFile' property
                var option0Name = Namer.GetOptionName("InputFile");
                var option0 = new System.CommandLine.Option<System.IO.FileInfo>
                (
                    option0Name
                )
                {
                    Required = false,
                    DefaultValueFactory = _ => new System.IO.FileInfo("default.txt"),
                    CustomParser = GetArgumentParser<System.IO.FileInfo>
                    (
                        null
                    ),
                };
                Namer.AddShortFormAlias(option0, "InputFile");
                command.Add(option0);

                // Option for 'DriveType' property
                var option1Name = Namer.GetOptionName("DriveType");
                var option1 = new System.CommandLine.Option<System.IO.DriveType>
                (
                    option1Name
                )
                {
                    Required = false,
                    DefaultValueFactory = _ => System.IO.DriveType.Fixed,
                    CustomParser = GetArgumentParser<System.IO.DriveType>
                    (
                        null
                    ),
                };
                Namer.AddShortFormAlias(option1, "DriveType");
                command.Add(option1);

                Binder = (parseResult) =>
                {
                    var targetClass = CreateInstance();

                    //  Set the values for the parent command accessors

                    //  Set the parsed or default values for the directives

                    //  Set the parsed or default values for the options
                    targetClass.InputFile = GetValueForOption(parseResult, option0);
                    targetClass.DriveType = GetValueForOption(parseResult, option1);

                    //  Set the parsed or default values for the arguments

                    return targetClass;
                };

                command.SetAction(parseResult =>
                {
                    var targetClass = (TestApp.Commands.PartialCliCommand.PartialNestedCliCommand) Bind(parseResult);

                    //  Call the command handler
                    var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                    var exitCode = 0;
                    targetClass.Run();

                    return exitCode;
                });

                return command;
            }

            [System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new TestApp.Commands.GeneratedCode.PartialCliCommandBuilder.PartialNestedCliCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }
    }
}
