// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.0.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.46508
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class RootSnakeSlashCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public RootSnakeSlashCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.RootSnakeSlashCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = global::DotMake.CommandLine.CliNameCasingConvention.SnakeCase;
            NamePrefixConvention = global::DotMake.CommandLine.CliNamePrefixConvention.ForwardSlash;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = global::DotMake.CommandLine.CliNamePrefixConvention.ForwardSlash;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'RootSnakeSlashCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("RootSnakeSlashCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            command.Description = "A cli command with snake_case name casing and forward slash prefix conventions";
            Namer.AddShortFormAlias(command, "RootSnakeSlashCliCommand");

            // Option for 'Option1' property
            var option0 = new global::System.CommandLine.Option<string>
            (
                Namer.GetOptionName("Option1")
            )
            {
                Description = "Description for Option1",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption1",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Option1");
            command.Add(option0);

            // Argument for 'Argument1' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("Argument1")
            )
            {
                Description = "Description for Argument1",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.RootSnakeSlashCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.RootSnakeSlashCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.Option1 = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.Argument1 = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.RootSnakeSlashCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                cliContext.ShowHelp();

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.RootSnakeSlashCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
