// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.8.2.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.41305
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class RootWithMixedChildrenCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public RootWithMixedChildrenCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.RootWithMixedChildrenCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'RootWithMixedChildrenCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("RootWithMixedChildrenCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            command.Description = "A root cli command with external children and one nested child and testing settings inheritance";
            Namer.AddShortFormAlias(command, "RootWithMixedChildrenCliCommand");

            // Option for 'Option1' property
            var option0 = new global::System.CommandLine.Option<string>
            (
                Namer.GetOptionName("Option1")
            )
            {
                Description = "Description for Option1",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption1",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Option1");
            command.Add(option0);

            // Argument for 'Argument1' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("Argument1")
            )
            {
                Description = "Description for Argument1",
                DefaultValueFactory = _ => "DefaultForArgument1",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.RootWithMixedChildrenCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.RootWithMixedChildrenCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.Option1 = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.Argument1 = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.RootWithMixedChildrenCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.RootWithMixedChildrenCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class Level1SubCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public Level1SubCliCommandBuilder()
            {
                DefinitionType = typeof(global::TestApp.Commands.RootWithMixedChildrenCliCommand.Level1SubCliCommand);
                ParentDefinitionType = typeof(global::TestApp.Commands.RootWithMixedChildrenCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = global::DotMake.CommandLine.CliNameCasingConvention.SnakeCase;
                NamePrefixConvention = global::DotMake.CommandLine.CliNamePrefixConvention.ForwardSlash;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = global::DotMake.CommandLine.CliNamePrefixConvention.ForwardSlash;
            }

            /// <inheritdoc />
            protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
            {
                // Command for 'Level1SubCliCommand' class
                var command = IsRoot
                    ? new global::System.CommandLine.RootCommand()
                    : new global::System.CommandLine.Command
                    (
                        Namer.GetCommandName("Level1SubCliCommand")
                    );
                var rootCommand = command as global::System.CommandLine.RootCommand;
                command.Description = "A nested level 1 sub-command with custom settings, throws test exception";
                Namer.AddShortFormAlias(command, "Level1SubCliCommand");

                // Option for 'Option1' property
                var option0 = new global::System.CommandLine.Option<string>
                (
                    Namer.GetOptionName("Option1")
                )
                {
                    Description = "Description for Option1",
                    Required = false,
                    DefaultValueFactory = _ => "DefaultForOption1",
                    CustomParser = bindingContext.GetArgumentParser<string>
                    (
                        null
                    ),
                };
                Namer.AddShortFormAlias(option0, "Option1");
                command.Add(option0);

                // Argument for 'Argument1' property
                var argument0 = new global::System.CommandLine.Argument<string>
                (
                    Namer.GetArgumentName("Argument1")
                )
                {
                    Description = "Description for Argument1",
                    CustomParser = bindingContext.GetArgumentParser<string>
                    (
                        null
                    ),
                };
                command.Add(argument0);

                bindingContext.CommandMap[command] = DefinitionType;
                bindingContext.CreatorMap[DefinitionType] = () =>
                {
                    return new global::TestApp.Commands.RootWithMixedChildrenCliCommand.Level1SubCliCommand();
                };
                bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                {
                    var definitionInstance = (global::TestApp.Commands.RootWithMixedChildrenCliCommand.Level1SubCliCommand)instance;

                    // Set the values for the command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options
                    definitionInstance.Option1 = bindingContext.GetValue(parseResult, option0);

                    // Set the parsed or default values for the arguments
                    definitionInstance.Argument1 = bindingContext.GetValue(parseResult, argument0);
                };

                command.SetAction(parseResult =>
                {
                    var definitionInstance = bindingContext.Bind<global::TestApp.Commands.RootWithMixedChildrenCliCommand.Level1SubCliCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    definitionInstance.Run();

                    return exitCode;
                });

                return command;
            }

            [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new global::TestApp.Commands.GeneratedCode.RootWithMixedChildrenCliCommandBuilder.Level1SubCliCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }
    }
}
