// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.6.4.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.27905
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class RootWithExternalChildrenCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public RootWithExternalChildrenCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.RootWithExternalChildrenCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = new [] 
            {
                typeof(TestApp.Commands.External.ExternalLevel1SubCliCommand)
            };
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'RootWithExternalChildrenCliCommand' class
            var commandName = Namer.GetCommandName("RootWithExternalChildrenCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            command.Description = "A root cli command with external children";
            Namer.AddShortFormAlias(command, "RootWithExternalChildrenCliCommand");

            // Option for 'Option1' property
            var option0Name = Namer.GetOptionName("Option1");
            var option0 = new System.CommandLine.Option<string>
            (
                option0Name
            )
            {
                Description = "Description for Option1",
                Required = false,
                DefaultValueFactory = _ => "DefaultForOption1",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Option1");
            command.Add(option0);

            // Argument for 'Argument1' property
            var argument0Name = Namer.GetArgumentName("Argument1");
            var argument0 = new System.CommandLine.Argument<string>
            (
                argument0Name
            )
            {
                Description = "Description for Argument1",
                DefaultValueFactory = _ => "DefaultForArgument1",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new TestApp.Commands.RootWithExternalChildrenCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (TestApp.Commands.RootWithExternalChildrenCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.Option1 = GetValueForOption(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.Argument1 = GetValueForArgument(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<TestApp.Commands.RootWithExternalChildrenCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.RootWithExternalChildrenCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
