// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v1.9.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1200.24.63101
// Generation: 1

namespace GeneratedCode
{
    /// <inheritdoc />
    public class CliCommandAsDelegate_4yk4pbmBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public CliCommandAsDelegate_4yk4pbmBuilder()
        {
            DefinitionType = typeof(GeneratedCode.CliCommandAsDelegate_4yk4pbm);
            ParentDefinitionType = null;
            NameCasingConvention = DotMake.CommandLine.CliNameCasingConvention.KebabCase;
            NamePrefixConvention = DotMake.CommandLine.CliNamePrefixConvention.DoubleHyphen;
            ShortFormPrefixConvention = DotMake.CommandLine.CliNamePrefixConvention.SingleHyphen;
            ShortFormAutoGenerate = true;
        }

        private GeneratedCode.CliCommandAsDelegate_4yk4pbm CreateInstance()
        {
            return new GeneratedCode.CliCommandAsDelegate_4yk4pbm();
        }

        /// <inheritdoc />
        public override System.CommandLine.Command Build()
        {
            // Command for 'CliCommandAsDelegate_4yk4pbm' class
            var rootCommand = new System.CommandLine.RootCommand()
            {
            };

            var defaultClass = CreateInstance();

            // Option for 'option2' property
            var option0 = new System.CommandLine.Option<bool>
            (
                "--option-2"
            )
            {
                Required = false,
                DefaultValueFactory = _ => defaultClass.option2,
                CustomParser = GetArgumentParser<bool>
                (
                    null
                ),
            };
            option0.Aliases.Add("-o");
            rootCommand.Add(option0);

            // Argument for 'argument2' property
            var argument0 = new System.CommandLine.Argument<string>
            (
                "argument-2"
            )
            {
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            rootCommand.Add(argument0);

            // Add nested or external registered children
            foreach (var child in Children)
            {
                rootCommand.Add(child.Build());
            }

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the parsed or default values for the options
                targetClass.option2 = GetValueForOption(parseResult, option0);

                //  Set the parsed or default values for the arguments
                targetClass.argument2 = GetValueForArgument(parseResult, argument0);

                //  Set the values for the parent command accessors

                return targetClass;
            };

            rootCommand.SetAction(parseResult =>
            {
                var targetClass = (GeneratedCode.CliCommandAsDelegate_4yk4pbm) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run();
                return exitCode;
            });

            return rootCommand;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new GeneratedCode.CliCommandAsDelegate_4yk4pbmBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
