// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.7.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.35903
// Generation: 1

namespace GeneratedCode
{
    /// <inheritdoc />
    public class CliCommandAsDelegate_dtqhqvwBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public CliCommandAsDelegate_dtqhqvwBuilder()
        {
            DefinitionType = typeof(GeneratedCode.CliCommandAsDelegate_dtqhqvw);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'CliCommandAsDelegate_dtqhqvw' class
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command
                (
                    Namer.GetCommandName("CliCommandAsDelegate_dtqhqvw")
                );
            var rootCommand = command as System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "CliCommandAsDelegate_dtqhqvw");

            // Option for 'option1' property
            var option0 = new System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("option1")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "option1");
            command.Add(option0);

            // Argument for 'argument1' property
            var argument0 = new System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("argument1")
            )
            {
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new GeneratedCode.CliCommandAsDelegate_dtqhqvw();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (GeneratedCode.CliCommandAsDelegate_dtqhqvw)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.option1 = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.argument1 = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<GeneratedCode.CliCommandAsDelegate_dtqhqvw>(parseResult);

                // Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                exitCode = definitionInstance.Run();

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new GeneratedCode.CliCommandAsDelegate_dtqhqvwBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
