// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.5.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.27905
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class DirectiveCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public DirectiveCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.DirectiveCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.DirectiveCliCommand CreateInstance()
        {
            return new TestApp.Commands.DirectiveCliCommand();
        }

        /// <inheritdoc />
        public override System.CommandLine.Command Build()
        {
            var namer = new DotMake.CommandLine.CliNamer
            (
                NameAutoGenerate,
                NameCasingConvention,
                NamePrefixConvention,
                ShortFormAutoGenerate,
                ShortFormPrefixConvention
            );

            // Command for 'DirectiveCliCommand' class
            var commandName = namer.GetCommandName("Directive", false);
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            command.Description = "A root cli command with directives";
            namer.AddShortFormAlias(command, commandName, false);

            // Directive for 'Debug' property
            var directive0Name = namer.GetDirectiveName("Debug", false);
            var directive0 = new System.CommandLine.Directive
            (
                directive0Name
            )
            {
            };
            rootCommand?.Add(directive0);

            // Directive for 'Directive2' property
            var directive1Name = namer.GetDirectiveName("Directive2", false);
            var directive1 = new System.CommandLine.Directive
            (
                directive1Name
            )
            {
            };
            rootCommand?.Add(directive1);

            // Directive for 'Vars' property
            var directive2Name = namer.GetDirectiveName("Vars", false);
            var directive2 = new System.CommandLine.Directive
            (
                directive2Name
            )
            {
            };
            rootCommand?.Add(directive2);

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the parsed or default values for the directives
                targetClass.Debug = GetValueForDirective<bool>(parseResult, directive0);
                targetClass.Directive2 = GetValueForDirective<string>(parseResult, directive1);
                targetClass.Vars = GetValueForDirective<string[]>(parseResult, directive2);

                //  Set the parsed or default values for the options

                //  Set the parsed or default values for the arguments

                //  Set the values for the parent command accessors

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = (TestApp.Commands.DirectiveCliCommand) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.DirectiveCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
