// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.0.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.46508
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class DirectiveCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public DirectiveCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.DirectiveCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'DirectiveCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("DirectiveCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            command.Description = "A root cli command with directives";
            Namer.AddShortFormAlias(command, "DirectiveCliCommand");

            // Directive for 'Debug' property
            var directive0 = new global::System.CommandLine.Directive
            (
                Namer.GetDirectiveName("Debug")
            )
            {
            };
            rootCommand?.Add(directive0);

            // Directive for 'Directive2' property
            var directive1 = new global::System.CommandLine.Directive
            (
                Namer.GetDirectiveName("Directive2")
            )
            {
            };
            rootCommand?.Add(directive1);

            // Directive for 'Vars' property
            var directive2 = new global::System.CommandLine.Directive
            (
                Namer.GetDirectiveName("Vars")
            )
            {
            };
            rootCommand?.Add(directive2);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.DirectiveCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.DirectiveCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives
                definitionInstance.Debug = bindingContext.GetValue<bool>(parseResult, directive0);
                definitionInstance.Directive2 = bindingContext.GetValue<string>(parseResult, directive1);
                definitionInstance.Vars = bindingContext.GetValue<string[]>(parseResult, directive2);

                // Set the parsed or default values for the options

                // Set the parsed or default values for the arguments
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.DirectiveCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.DirectiveCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class Level1CliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public Level1CliCommandBuilder()
            {
                DefinitionType = typeof(global::TestApp.Commands.DirectiveCliCommand.Level1CliCommand);
                ParentDefinitionType = typeof(global::TestApp.Commands.DirectiveCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            /// <inheritdoc />
            protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
            {
                // Command for 'Level1CliCommand' class
                var command = IsRoot
                    ? new global::System.CommandLine.RootCommand()
                    : new global::System.CommandLine.Command
                    (
                        Namer.GetCommandName("Level1CliCommand")
                    );
                var rootCommand = command as global::System.CommandLine.RootCommand;
                command.Description = "A sub cli command with directives";
                Namer.AddShortFormAlias(command, "Level1CliCommand");

                bindingContext.CommandMap[command] = DefinitionType;
                bindingContext.CreatorMap[DefinitionType] = () =>
                {
                    return new global::TestApp.Commands.DirectiveCliCommand.Level1CliCommand();
                };
                bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                {
                    var definitionInstance = (global::TestApp.Commands.DirectiveCliCommand.Level1CliCommand)instance;

                    // Set the values for the command accessors
                    definitionInstance.Parent = bindingContext.Bind<global::TestApp.Commands.DirectiveCliCommand>(parseResult);

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options

                    // Set the parsed or default values for the arguments
                };

                command.SetAction(parseResult =>
                {
                    var definitionInstance = bindingContext.Bind<global::TestApp.Commands.DirectiveCliCommand.Level1CliCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    definitionInstance.Run(cliContext);

                    return exitCode;
                });

                return command;
            }

            [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new global::TestApp.Commands.GeneratedCode.DirectiveCliCommandBuilder.Level1CliCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }
    }
}
