// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.0.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.46508
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class GetCompletionsCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public GetCompletionsCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.GetCompletionsCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }


        private global::System.Collections.Generic.IEnumerable<global::System.CommandLine.Completions.CompletionItem> GetCompletions(
            string propertyName, global::DotMake.CommandLine.CliBindingContext bindingContext, global::System.CommandLine.Completions.CompletionContext completionContext)
        {
            var definitionInstance = bindingContext.Bind<global::TestApp.Commands.GetCompletionsCliCommand>(completionContext.ParseResult, true);

            // Call the interface method with property name of option or argument
            return definitionInstance.GetCompletions(propertyName, completionContext);
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'GetCompletionsCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("GetCompletionsCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            command.Description = "A root cli command with completions for options and arguments";
            Namer.AddShortFormAlias(command, "GetCompletionsCliCommand");

            // Option for 'DateOption' property
            var option0 = new global::System.CommandLine.Option<global::System.DateTime>
            (
                Namer.GetOptionName("DateOption")
            )
            {
                Description = "Description for DateOption",
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<global::System.DateTime>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "DateOption");
            option0.CompletionSources.Add(completionContext => GetCompletions("DateOption", bindingContext, completionContext));
            command.Add(option0);

            // Argument for 'FruitArgument' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("FruitArgument")
            )
            {
                Description = "Description for FruitArgument",
                DefaultValueFactory = _ => "DefaultForFruitArgument",
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            argument0.CompletionSources.Add(completionContext => GetCompletions("FruitArgument", bindingContext, completionContext));
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.GetCompletionsCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.GetCompletionsCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.DateOption = bindingContext.GetValue(parseResult, option0);

                // Set the parsed or default values for the arguments
                definitionInstance.FruitArgument = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.GetCompletionsCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.GetCompletionsCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
