// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.6.0.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.26210
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class GetCompletionsCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public GetCompletionsCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.GetCompletionsCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.GetCompletionsCliCommand CreateInstance()
        {
            return new TestApp.Commands.GetCompletionsCliCommand();
        }


        private System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem> GetCompletions(
            string propertyName, System.CommandLine.Completions.CompletionContext completionContext)
        {
            var targetClass = (TestApp.Commands.GetCompletionsCliCommand) Bind(completionContext.ParseResult);

            //  Call the interface method with property name of option or argument
            return targetClass.GetCompletions(propertyName, completionContext);
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild()
        {
            // Command for 'GetCompletionsCliCommand' class
            var commandName = Namer.GetCommandName("GetCompletionsCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            command.Description = "A root cli command with completions for options and arguments";
            Namer.AddShortFormAlias(command, "GetCompletionsCliCommand");

            // Option for 'DateOption' property
            var option0Name = Namer.GetOptionName("DateOption");
            var option0 = new System.CommandLine.Option<System.DateTime>
            (
                option0Name
            )
            {
                Description = "Description for DateOption",
                Required = false,
                CustomParser = GetArgumentParser<System.DateTime>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "DateOption");
            option0.CompletionSources.Add(completionContext => GetCompletions("DateOption", completionContext));
            command.Add(option0);

            // Argument for 'FruitArgument' property
            var argument0Name = Namer.GetArgumentName("FruitArgument");
            var argument0 = new System.CommandLine.Argument<string>
            (
                argument0Name
            )
            {
                Description = "Description for FruitArgument",
                DefaultValueFactory = _ => "DefaultForFruitArgument",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            argument0.CompletionSources.Add(completionContext => GetCompletions("FruitArgument", completionContext));
            command.Add(argument0);

            Binder = (parseResult) =>
            {
                var targetClass = CreateInstance();

                //  Set the values for the parent command accessors

                //  Set the parsed or default values for the directives

                //  Set the parsed or default values for the options
                targetClass.DateOption = GetValueForOption(parseResult, option0);

                //  Set the parsed or default values for the arguments
                targetClass.FruitArgument = GetValueForArgument(parseResult, argument0);

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = (TestApp.Commands.GetCompletionsCliCommand) Bind(parseResult);

                //  Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(parseResult);
                var exitCode = 0;
                targetClass.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.GetCompletionsCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
