// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.5.0.0
// Roslyn (Microsoft.CodeAnalysis) v5.300.26.18118
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class MutualExclusiveCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public MutualExclusiveCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.MutualExclusiveCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            var namer = bindingContext.NamerMap[this];

            // Command for 'MutualExclusiveCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    namer.GetCommandName("MutualExclusiveCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            namer.AddShortFormAlias(command, "MutualExclusiveCliCommand");

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.MutualExclusiveCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.MutualExclusiveCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options

                // Set the parsed or default values for the arguments
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.MutualExclusiveCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                cliContext.ShowHelp();

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.MutualExclusiveCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class FormatCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public FormatCommandBuilder()
            {
                DefinitionType = typeof(global::TestApp.Commands.MutualExclusiveCliCommand.FormatCommand);
                ParentDefinitionType = typeof(global::TestApp.Commands.MutualExclusiveCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            /// <inheritdoc />
            protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
            {
                var namer = bindingContext.NamerMap[this];

                // Command for 'FormatCommand' class
                var command = IsRoot
                    ? new global::System.CommandLine.RootCommand()
                    : new global::System.CommandLine.Command
                    (
                        namer.GetCommandName("FormatCommand")
                    );
                var rootCommand = command as global::System.CommandLine.RootCommand;
                command.Description = "Display different file formats";
                namer.AddShortFormAlias(command, "FormatCommand");

                // Option for 'Xml' property
                var option0 = new global::System.CommandLine.Option<bool>
                (
                    namer.GetOptionName("Xml")
                )
                {
                    Description = "Output as XML" + " [Group: 'Format']",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<bool>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option0, "Xml");
                command.Add(option0);

                // Option for 'Json' property
                var option1 = new global::System.CommandLine.Option<bool>
                (
                    namer.GetOptionName("Json")
                )
                {
                    Description = "Output as JSON" + " [Group: 'Format']",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<bool>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option1, "Json");
                command.Add(option1);

                // Option for 'Verbose' property
                var option2 = new global::System.CommandLine.Option<string>
                (
                    namer.GetOptionName("Verbose")
                )
                {
                    Description = "Verbosity level",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<string>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option2, "Verbose");
                command.Add(option2);

                // Validator for mutually exclusive option group 'Format' [not required]
                global::DotMake.CommandLine.CliValidationExtensions.AddGroupValidator(command, "Format", false, option0, option1);

                bindingContext.CommandMap[command] = DefinitionType;
                bindingContext.CreatorMap[DefinitionType] = () =>
                {
                    return new global::TestApp.Commands.MutualExclusiveCliCommand.FormatCommand();
                };
                bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                {
                    var definitionInstance = (global::TestApp.Commands.MutualExclusiveCliCommand.FormatCommand)instance;

                    // Set the values for the command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options
                    definitionInstance.Xml = bindingContext.GetValue(parseResult, option0);
                    definitionInstance.Json = bindingContext.GetValue(parseResult, option1);
                    definitionInstance.Verbose = bindingContext.GetValue(parseResult, option2);

                    // Set the parsed or default values for the arguments
                };

                command.SetAction(parseResult =>
                {
                    var definitionInstance = bindingContext.Bind<global::TestApp.Commands.MutualExclusiveCliCommand.FormatCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    definitionInstance.Run(cliContext);

                    return exitCode;
                });

                return command;
            }

            [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new global::TestApp.Commands.GeneratedCode.MutualExclusiveCliCommandBuilder.FormatCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }

        /// <inheritdoc />
        public class ReportCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public ReportCommandBuilder()
            {
                DefinitionType = typeof(global::TestApp.Commands.MutualExclusiveCliCommand.ReportCommand);
                ParentDefinitionType = typeof(global::TestApp.Commands.MutualExclusiveCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            /// <inheritdoc />
            protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
            {
                var namer = bindingContext.NamerMap[this];

                // Command for 'ReportCommand' class
                var command = IsRoot
                    ? new global::System.CommandLine.RootCommand()
                    : new global::System.CommandLine.Command
                    (
                        namer.GetCommandName("ReportCommand")
                    );
                var rootCommand = command as global::System.CommandLine.RootCommand;
                command.Description = "Generate a report with a chosen output format. Requires authentication via API key or token.";
                namer.AddShortFormAlias(command, "ReportCommand");

                // Option for 'Json' property
                var option0 = new global::System.CommandLine.Option<bool>
                (
                    namer.GetOptionName("Json")
                )
                {
                    Description = "Output the report in JSON format." + " [Group: 'output-format']",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<bool>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option0, "Json");
                command.Add(option0);

                // Option for 'Xml' property
                var option1 = new global::System.CommandLine.Option<bool>
                (
                    namer.GetOptionName("Xml")
                )
                {
                    Description = "Output the report in XML format." + " [Group: 'output-format']",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<bool>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option1, "Xml");
                command.Add(option1);

                // Option for 'ApiKey' property
                var option2 = new global::System.CommandLine.Option<string>
                (
                    namer.GetOptionName("ApiKey")
                )
                {
                    Description = "Authenticate using an API key (exactly one of --apikey or --token must be provided)." + " [Group: 'auth', required]",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<string>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option2, "ApiKey");
                command.Add(option2);

                // Option for 'Token' property
                var option3 = new global::System.CommandLine.Option<string>
                (
                    namer.GetOptionName("Token")
                )
                {
                    Description = "Authenticate using a bearer token (exactly one of --apikey or --token must be provided)." + " [Group: 'auth', required]",
                    Required = false,
                    CustomParser = bindingContext.GetArgumentParser<string>
                    (
                        null
                    ),
                };
                namer.AddShortFormAlias(option3, "Token");
                command.Add(option3);

                // Validator for mutually exclusive option group 'output-format' [not required]
                global::DotMake.CommandLine.CliValidationExtensions.AddGroupValidator(command, "output-format", false, option0, option1);

                // Validator for mutually exclusive option group 'auth' [required]
                global::DotMake.CommandLine.CliValidationExtensions.AddGroupValidator(command, "auth", true, option2, option3);

                bindingContext.CommandMap[command] = DefinitionType;
                bindingContext.CreatorMap[DefinitionType] = () =>
                {
                    return new global::TestApp.Commands.MutualExclusiveCliCommand.ReportCommand();
                };
                bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
                {
                    var definitionInstance = (global::TestApp.Commands.MutualExclusiveCliCommand.ReportCommand)instance;

                    // Set the values for the command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options
                    definitionInstance.Json = bindingContext.GetValue(parseResult, option0);
                    definitionInstance.Xml = bindingContext.GetValue(parseResult, option1);
                    definitionInstance.ApiKey = bindingContext.GetValue(parseResult, option2);
                    definitionInstance.Token = bindingContext.GetValue(parseResult, option3);

                    // Set the parsed or default values for the arguments
                };

                command.SetAction(parseResult =>
                {
                    var definitionInstance = bindingContext.Bind<global::TestApp.Commands.MutualExclusiveCliCommand.ReportCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    definitionInstance.Run(cliContext);

                    return exitCode;
                });

                return command;
            }

            [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new global::TestApp.Commands.GeneratedCode.MutualExclusiveCliCommandBuilder.ReportCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }
    }
}
