// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.8.2.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.41305
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class OptionBundlingCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public OptionBundlingCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.OptionBundlingCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'OptionBundlingCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("OptionBundlingCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "OptionBundlingCliCommand");

            // Option for 'A' property
            var option0 = new global::System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("A", "-a")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "A");
            command.Add(option0);

            // Option for 'B' property
            var option1 = new global::System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("B", "-b")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option1, "B");
            command.Add(option1);

            // Option for 'C' property
            var option2 = new global::System.CommandLine.Option<bool>
            (
                Namer.GetOptionName("C", "-c")
            )
            {
                Required = false,
                CustomParser = bindingContext.GetArgumentParser<bool>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option2, "C");
            command.Add(option2);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.OptionBundlingCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.OptionBundlingCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                definitionInstance.A = bindingContext.GetValue(parseResult, option0);
                definitionInstance.B = bindingContext.GetValue(parseResult, option1);
                definitionInstance.C = bindingContext.GetValue(parseResult, option2);

                // Set the parsed or default values for the arguments
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.OptionBundlingCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                definitionInstance.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.GeneratedCode.OptionBundlingCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
