// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v2.6.2.0
// Roslyn (Microsoft.CodeAnalysis) v4.1400.25.26210
// Generation: 1

namespace TestApp.Commands.GeneratedCode
{
    /// <inheritdoc />
    public class ShortFormCliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public ShortFormCliCommandBuilder()
        {
            DefinitionType = typeof(TestApp.Commands.ShortFormCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        private TestApp.Commands.ShortFormCliCommand CreateInstance()
        {
            return new TestApp.Commands.ShortFormCliCommand();
        }

        /// <inheritdoc />
        protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'ShortFormCliCommand' class
            var commandName = Namer.GetCommandName("ShortFormCliCommand");
            var command = IsRoot
                ? new System.CommandLine.RootCommand()
                : new System.CommandLine.Command(commandName);
            var rootCommand = command as System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "ShortFormCliCommand");

            // Option for 'Oauth2GrantType' property
            var option0Name = Namer.GetOptionName("Oauth2GrantType");
            var option0 = new System.CommandLine.Option<string>
            (
                option0Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option0, "Oauth2GrantType", "o2");
            command.Add(option0);

            // Option for 'Oauth2TokenUrl' property
            var option1Name = Namer.GetOptionName("Oauth2TokenUrl");
            var option1 = new System.CommandLine.Option<string>
            (
                option1Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option1, "Oauth2TokenUrl");
            command.Add(option1);

            // Option for 'Oauth2ClientId' property
            var option2Name = Namer.GetOptionName("Oauth2ClientId");
            var option2 = new System.CommandLine.Option<string>
            (
                option2Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option2, "Oauth2ClientId");
            command.Add(option2);

            // Option for 'Oauth2ClientSecret' property
            var option3Name = Namer.GetOptionName("Oauth2ClientSecret");
            var option3 = new System.CommandLine.Option<string>
            (
                option3Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option3, "Oauth2ClientSecret");
            command.Add(option3);

            // Option for 'Sha256' property
            var option4Name = Namer.GetOptionName("Sha256");
            var option4 = new System.CommandLine.Option<string>
            (
                option4Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option4, "Sha256");
            command.Add(option4);

            // Option for 'Option1' property
            var option5Name = Namer.GetOptionName("Option1");
            var option5 = new System.CommandLine.Option<string>
            (
                option5Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option5, "Option1");
            Namer.AddAlias(option5, "Option1", " ");
            Namer.AddAlias(option5, "Option1", "opt1");
            command.Add(option5);

            // Option for 'Option1Option' property
            var option6Name = Namer.GetOptionName("Option1Option");
            var option6 = new System.CommandLine.Option<string>
            (
                option6Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option6, "Option1Option");
            command.Add(option6);

            // Option for 'Option2' property
            var option7Name = Namer.GetOptionName("Option2");
            var option7 = new System.CommandLine.Option<string>
            (
                option7Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option7, "Option2", "-o2o");
            Namer.AddAlias(option7, "Option2", "/opt2");
            command.Add(option7);

            // Option for 'Option3' property
            var option8Name = Namer.GetOptionName("Option3", "opt3");
            var option8 = new System.CommandLine.Option<string>
            (
                option8Name
            )
            {
                Required = false,
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            Namer.AddShortFormAlias(option8, "Option3", "/opt3");
            Namer.AddAlias(option8, "Option3", "-opt3");
            command.Add(option8);

            // Argument for 'Argument1' property
            var argument0Name = Namer.GetArgumentName("Argument1");
            var argument0 = new System.CommandLine.Argument<string>
            (
                argument0Name
            )
            {
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            // Argument for 'Argument1Argument' property
            var argument1Name = Namer.GetArgumentName("Argument1Argument");
            var argument1 = new System.CommandLine.Argument<string>
            (
                argument1Name
            )
            {
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument1);

            // Argument for 'Option1Argument' property
            var argument2Name = Namer.GetArgumentName("Option1Argument");
            var argument2 = new System.CommandLine.Argument<string>
            (
                argument2Name
            )
            {
                DefaultValueFactory = _ => "",
                CustomParser = GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument2);

            bindingContext.Binders[DefinitionType] = (parseResult) =>
            {
                var targetClass = CreateInstance();

                // Set the values for the parent command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options
                targetClass.Oauth2GrantType = GetValueForOption(parseResult, option0);
                targetClass.Oauth2TokenUrl = GetValueForOption(parseResult, option1);
                targetClass.Oauth2ClientId = GetValueForOption(parseResult, option2);
                targetClass.Oauth2ClientSecret = GetValueForOption(parseResult, option3);
                targetClass.Sha256 = GetValueForOption(parseResult, option4);
                targetClass.Option1 = GetValueForOption(parseResult, option5);
                targetClass.Option1Option = GetValueForOption(parseResult, option6);
                targetClass.Option2 = GetValueForOption(parseResult, option7);
                targetClass.Option3 = GetValueForOption(parseResult, option8);

                // Set the parsed or default values for the arguments
                targetClass.Argument1 = GetValueForArgument(parseResult, argument0);
                targetClass.Argument1Argument = GetValueForArgument(parseResult, argument1);
                targetClass.Option1Argument = GetValueForArgument(parseResult, argument2);

                return targetClass;
            };

            command.SetAction(parseResult =>
            {
                var targetClass = bindingContext.Bind<TestApp.Commands.ShortFormCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                targetClass.Run(cliContext);

                return exitCode;
            });

            return command;
        }

        [System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new TestApp.Commands.GeneratedCode.ShortFormCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }

        /// <inheritdoc />
        public class TestCommandBuilder : DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public TestCommandBuilder()
            {
                DefinitionType = typeof(TestApp.Commands.ShortFormCliCommand.TestCommand);
                ParentDefinitionType = typeof(TestApp.Commands.ShortFormCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            private TestApp.Commands.ShortFormCliCommand.TestCommand CreateInstance()
            {
                return new TestApp.Commands.ShortFormCliCommand.TestCommand();
            }

            /// <inheritdoc />
            protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
            {
                // Command for 'TestCommand' class
                var commandName = Namer.GetCommandName("TestCommand");
                var command = IsRoot
                    ? new System.CommandLine.RootCommand()
                    : new System.CommandLine.Command(commandName);
                var rootCommand = command as System.CommandLine.RootCommand;
                Namer.AddShortFormAlias(command, "TestCommand");

                bindingContext.Binders[DefinitionType] = (parseResult) =>
                {
                    var targetClass = CreateInstance();

                    // Set the values for the parent command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options

                    // Set the parsed or default values for the arguments

                    return targetClass;
                };

                command.SetAction(parseResult =>
                {
                    var targetClass = bindingContext.Bind<TestApp.Commands.ShortFormCliCommand.TestCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    cliContext.ShowHelp();

                    return exitCode;
                });

                return command;
            }

            [System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new TestApp.Commands.GeneratedCode.ShortFormCliCommandBuilder.TestCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }

        /// <inheritdoc />
        public class Option1CommandBuilder : DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public Option1CommandBuilder()
            {
                DefinitionType = typeof(TestApp.Commands.ShortFormCliCommand.Option1Command);
                ParentDefinitionType = typeof(TestApp.Commands.ShortFormCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            private TestApp.Commands.ShortFormCliCommand.Option1Command CreateInstance()
            {
                return new TestApp.Commands.ShortFormCliCommand.Option1Command();
            }

            /// <inheritdoc />
            protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
            {
                // Command for 'Option1Command' class
                var commandName = Namer.GetCommandName("Option1Command");
                var command = IsRoot
                    ? new System.CommandLine.RootCommand()
                    : new System.CommandLine.Command(commandName);
                var rootCommand = command as System.CommandLine.RootCommand;
                Namer.AddShortFormAlias(command, "Option1Command");
                Namer.AddAlias(command, "Option1Command", "op1");

                bindingContext.Binders[DefinitionType] = (parseResult) =>
                {
                    var targetClass = CreateInstance();

                    // Set the values for the parent command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options

                    // Set the parsed or default values for the arguments

                    return targetClass;
                };

                command.SetAction(parseResult =>
                {
                    var targetClass = bindingContext.Bind<TestApp.Commands.ShortFormCliCommand.Option1Command>(parseResult);

                    // Call the command handler
                    var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    cliContext.ShowHelp();

                    return exitCode;
                });

                return command;
            }

            [System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new TestApp.Commands.GeneratedCode.ShortFormCliCommandBuilder.Option1CommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }

        /// <inheritdoc />
        public class CliCommandBuilder : DotMake.CommandLine.CliCommandBuilder
        {
            /// <inheritdoc />
            public CliCommandBuilder()
            {
                DefinitionType = typeof(TestApp.Commands.ShortFormCliCommand.CliCommand);
                ParentDefinitionType = typeof(TestApp.Commands.ShortFormCliCommand);
                ChildDefinitionTypes = null;
                NameAutoGenerate = null;
                NameCasingConvention = null;
                NamePrefixConvention = null;
                ShortFormAutoGenerate = null;
                ShortFormPrefixConvention = null;
            }

            private TestApp.Commands.ShortFormCliCommand.CliCommand CreateInstance()
            {
                return new TestApp.Commands.ShortFormCliCommand.CliCommand();
            }

            /// <inheritdoc />
            protected override System.CommandLine.Command DoBuild(DotMake.CommandLine.CliBindingContext bindingContext)
            {
                // Command for 'CliCommand' class
                var commandName = Namer.GetCommandName("CliCommand", "cmd");
                var command = IsRoot
                    ? new System.CommandLine.RootCommand()
                    : new System.CommandLine.Command(commandName);
                var rootCommand = command as System.CommandLine.RootCommand;
                Namer.AddShortFormAlias(command, "CliCommand", "cl");

                bindingContext.Binders[DefinitionType] = (parseResult) =>
                {
                    var targetClass = CreateInstance();

                    // Set the values for the parent command accessors

                    // Set the parsed or default values for the directives

                    // Set the parsed or default values for the options

                    // Set the parsed or default values for the arguments

                    return targetClass;
                };

                command.SetAction(parseResult =>
                {
                    var targetClass = bindingContext.Bind<TestApp.Commands.ShortFormCliCommand.CliCommand>(parseResult);

                    // Call the command handler
                    var cliContext = new DotMake.CommandLine.CliContext(bindingContext, parseResult);
                    var exitCode = 0;
                    cliContext.ShowHelp();

                    return exitCode;
                });

                return command;
            }

            [System.Runtime.CompilerServices.ModuleInitializerAttribute]
            internal static void Initialize()
            {
                var commandBuilder = new TestApp.Commands.GeneratedCode.ShortFormCliCommandBuilder.CliCommandBuilder();

                // Register this command builder so that it can be found by the definition class
                // and it can be found by the parent definition class if it's a nested/external child.
                commandBuilder.Register();
            }
        }
    }
}
