// <auto-generated />
// Generated by DotMake.CommandLine.SourceGeneration v3.1.0.0
// Roslyn (Microsoft.CodeAnalysis) v5.0.25.52411
// Generation: 1

namespace TestApp.Commands.TestApp.GeneratedCode
{
    /// <inheritdoc />
    public class TestAppCliCommandBuilder : global::DotMake.CommandLine.CliCommandBuilder
    {
        /// <inheritdoc />
        public TestAppCliCommandBuilder()
        {
            DefinitionType = typeof(global::TestApp.Commands.TestApp.TestAppCliCommand);
            ParentDefinitionType = null;
            ChildDefinitionTypes = null;
            NameAutoGenerate = null;
            NameCasingConvention = null;
            NamePrefixConvention = null;
            ShortFormAutoGenerate = null;
            ShortFormPrefixConvention = null;
        }

        /// <inheritdoc />
        protected override global::System.CommandLine.Command DoBuild(global::DotMake.CommandLine.CliBindingContext bindingContext)
        {
            // Command for 'TestAppCliCommand' class
            var command = IsRoot
                ? new global::System.CommandLine.RootCommand()
                : new global::System.CommandLine.Command
                (
                    Namer.GetCommandName("TestAppCliCommand")
                );
            var rootCommand = command as global::System.CommandLine.RootCommand;
            Namer.AddShortFormAlias(command, "TestAppCliCommand");

            // Argument for 'Arg' property
            var argument0 = new global::System.CommandLine.Argument<string>
            (
                Namer.GetArgumentName("Arg")
            )
            {
                Arity = global::System.CommandLine.ArgumentArity.ZeroOrMore,
                CustomParser = bindingContext.GetArgumentParser<string>
                (
                    null
                ),
            };
            command.Add(argument0);

            bindingContext.CommandMap[command] = DefinitionType;
            bindingContext.CreatorMap[DefinitionType] = () =>
            {
                return new global::TestApp.Commands.TestApp.TestAppCliCommand();
            };
            bindingContext.BinderMap[DefinitionType] = (instance, parseResult) =>
            {
                var definitionInstance = (global::TestApp.Commands.TestApp.TestAppCliCommand)instance;

                // Set the values for the command accessors

                // Set the parsed or default values for the directives

                // Set the parsed or default values for the options

                // Set the parsed or default values for the arguments
                definitionInstance.Arg = bindingContext.GetValue(parseResult, argument0);
            };

            command.SetAction(parseResult =>
            {
                var definitionInstance = bindingContext.Bind<global::TestApp.Commands.TestApp.TestAppCliCommand>(parseResult);

                // Call the command handler
                var cliContext = new global::DotMake.CommandLine.CliContext(bindingContext, parseResult);
                var exitCode = 0;
                cliContext.ShowHelp();

                return exitCode;
            });

            return command;
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        internal static void Initialize()
        {
            var commandBuilder = new global::TestApp.Commands.TestApp.GeneratedCode.TestAppCliCommandBuilder();

            // Register this command builder so that it can be found by the definition class
            // and it can be found by the parent definition class if it's a nested/external child.
            commandBuilder.Register();
        }
    }
}
