# Your GitHub workflow file under .github/workflows/

on:
  # Trigger the action when you create a release:
  release:
    types: [published]

  # also allow manual trigger on GitHub Actions panel:
  workflow_dispatch:

  # or trigger the action on push to main:
  #push:
  #  branches:
  #    - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x

    # Install latest version of docfx-plus tool:
    - run: dotnet tool update -g docfx-plus

    # Build docs in this repository via docfx-plus:
    - run: docfx-plus docs/docfx.json

    # Upload HTML output of the docs build:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: 'docs/_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
